defaults = {
    "world": "Shiva",
    "connectedWorlds": ["Lich", "Odin", "Phoenix", "Zodiark", "Twintania"],
    "retainerBL": [
        "Territum",
        "Teritum",
        "Tarvi",
        "Sharra",
        "Sashalle",
        "Sellshit",
        "Sellgarbage",
        "Sellcrap",
    ],
    "buyCraftLenience": 50,
    "crystalsCraftPrice": True,
    "removeUntradeableReagents": False,
    "blCurrentListings": True,
    "recentPriceN": 3,
    "recentPriceDays": 3,
}
